"""Add not null

Revision ID: 1b2413b48228
Revises: cb8ef8a8924c
Create Date: 2025-09-24 01:30:23.494998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b2413b48228'
down_revision: Union[str, Sequence[str], None] = 'cb8ef8a8924c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_tasks', 'file_bytes',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('scan_tasks', 'file_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_tasks', sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('scan_tasks', 'file_bytes',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
