"""updated all

Revision ID: 5a27d56983a8
Revises: 1b2413b48228
Create Date: 2025-09-24 02:26:19.900665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a27d56983a8'
down_revision: Union[str, Sequence[str], None] = '1b2413b48228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('apps', sa.Column('total_engines', sa.Integer(), nullable=True))
    op.add_column('apps', sa.Column('malicious_count', sa.Integer(), nullable=True))
    op.add_column('apps', sa.Column('suspicious_count', sa.Integer(), nullable=True))
    op.add_column('apps', sa.Column('harmless_count', sa.Integer(), nullable=True))
    op.add_column('apps', sa.Column('undetected_count', sa.Integer(), nullable=True))
    op.add_column('apps', sa.Column('scan_date', sa.DateTime(), nullable=True))
    op.alter_column('apps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_apps_file_hash'), 'apps', ['file_hash'], unique=False)
    op.add_column('detections', sa.Column('method', sa.String(), nullable=True))
    op.add_column('detections', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.alter_column('detections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_detections_file_hash'), 'detections', ['file_hash'], unique=False)
    op.add_column('malwares', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('malwares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('scan_tasks', sa.Column('scanning_hash', sa.String(length=64), nullable=True))
    op.alter_column('scan_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('scan_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_scan_tasks_scanning_hash'), 'scan_tasks', ['scanning_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_tasks_scanning_hash'), table_name='scan_tasks')
    op.alter_column('scan_tasks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('scan_tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('scan_tasks', 'scanning_hash')
    op.alter_column('malwares', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('malwares', 'category')
    op.drop_index(op.f('ix_detections_file_hash'), table_name='detections')
    op.alter_column('detections', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('detections', 'file_hash')
    op.drop_column('detections', 'method')
    op.drop_index(op.f('ix_apps_file_hash'), table_name='apps')
    op.alter_column('apps', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('apps', 'scan_date')
    op.drop_column('apps', 'undetected_count')
    op.drop_column('apps', 'harmless_count')
    op.drop_column('apps', 'suspicious_count')
    op.drop_column('apps', 'malicious_count')
    op.drop_column('apps', 'total_engines')
    op.drop_column('apps', 'file_hash')
    # ### end Alembic commands ###
