"""Add nullable file_bytes

Revision ID: 7b6a4401cadc
Revises: e7ca15cc0605
Create Date: 2025-09-24 01:10:39.682017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b6a4401cadc'
down_revision: Union[str, Sequence[str], None] = 'e7ca15cc0605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_tasks', 'file_bytes',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_tasks', 'file_bytes',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
