"""add default

Revision ID: 7c47b277bb65
Revises: d31ab8e71d59
Create Date: 2025-09-24 04:27:33.309194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c47b277bb65'
down_revision: Union[str, Sequence[str], None] = 'd31ab8e71d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_tasks', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_tasks', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
