"""add is_admin field with default value to user

Revision ID: c3bbf9f0c355
Revises: 4e82b3e5b583
Create Date: 2025-09-25 11:39:46.874946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bbf9f0c355'
down_revision: Union[str, Sequence[str], None] = '4e82b3e5b583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
