"""Add nullable file_hash

Revision ID: cb8ef8a8924c
Revises: 7b6a4401cadc
Create Date: 2025-09-24 01:16:31.139403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8ef8a8924c'
down_revision: Union[str, Sequence[str], None] = '7b6a4401cadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_tasks', sa.Column('file_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_tasks', 'file_hash')
    # ### end Alembic commands ###
