"""Add device_code to ScanTask

Revision ID: e7ca15cc0605
Revises: 6bc43560dfee
Create Date: 2025-09-23 23:47:09.165353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7ca15cc0605'
down_revision: Union[str, Sequence[str], None] = '6bc43560dfee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', 'timeout', name='scanstatus'),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_tasks', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'processing', 'completed', 'failed', 'timeout', name='scanstatus'),
               nullable=True)
    # ### end Alembic commands ###
